server:
  port: 80

cors:
  originPatterns: http://localhost:3000,http://localhost:8080
file:
  upload-dir: /Code/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000

email:
  subject: "Default Subject"
  message: "Default Message"

spring:
  application:
    name: erp-rest-spring-boot
  datasource:
    drive-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/erp_oliveira?useTimezone=true&serverTimezone=UTC
    #url: ${JDBC_URL}
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none   # pode ser 'validate', 'create', 'update' ou 'create-drop'
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
     hibernate:
    show-sql: false        # opcional, Ãºtil para debug
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

#FlyWay
flyway:
  url=jdbc:postgresql://localhost:5432/
  schemas=erp_oliveira
  user=postgres
  password=admin123

logging:
  level:
    root: INFO #Padrao Info
    #org.springframework.boot : TRACE
    #net.sf.jasperreports.engine.*: TRACE
    #br.com.oliveirawillian: DEBUG


spring-doc:
  paths-to-match:
    - /auth/**
    - /api/**/v1/**

  swagger-ui:
    use-root-path: true

